### ISSUE TITLE
Processed Data sets

### ISSUE THREAD

**Issue by ZhenZHAO** [kimjisoo12/GuidedNet#2]
Hi,

Thanks for your excellent job. I saw your code read in data in a format of h5. Can you kindly share the processed datasets and also the training splits?

Bests

**Comment by kimjisoo12** [comment]
Thank you for your inquiry, and I sincerely apologize for the delayed response due to working against a paper deadline. The fully preprocessed h5 data from FLARE 2022 and AMOS has been uploaded to Baidu Netdisk. Please find the link below:

Link: https://pan.baidu.com/s/1YISYVgZow2NpEYUlV6J8Dw
Access Code: kaf6

We have also uploaded the preprocessing code for the original datasets. Once again, I apologize for the delayed response and hope you understand.

**Comment by ZhenZHAO** [comment]
Thanks! appreciate it.

**Comment by ZhenZHAO** [comment]
Can you help to check the uploaded fie? I found some of the training instance are mising.

e.g.,, 2022_flare/train_004, 2022_flare/train_003 is not found.

I also found there are more instances than we used in .txt file. Are we supposed to use all of them?

**Comment by kimjisoo12** [comment]
Apologies, please allow us to review it, and we will make corrections shortly.

**Comment by kimjisoo12** [comment]
> Can you help to check the uploaded fie? I found some of the training instance are mising.
> 
> e.g.,, 2022_flare/train_004, 2022_flare/train_003 is not found.
> 
> I also found there are more instances than we used in .txt file. Are we supposed to use all of them?

Apologies, we have updated the training data. The flare dataset contains a total of 490 h5 files, including 462 for the training set (42 labeled + 42 unlabeled or 42 labeled + 420 unlabeled), 14 for validation, and 14 for testing. The amos dataset consists of 180 training files, 60 validation files, and 60 test files. Please check.
Link: https://pan.baidu.com/s/1aUDUu3iVfrlrVidcJmOkcg?pwd=1fvb
Access Code: 1fvb

**Comment by ZhenZHAO** [comment]
Thanks. But Check your Table1, and text file for 2022_flare, there are supposed to be 420 for training in total. Can you leave your wechat or add my wechat(account: umzhen) for further discussion?
